#  Match de palabras

In [2]:
from fuzzywuzzy import process
import pandas as pd

In [3]:
#Se lee el archivo al que se quiere buscar las columnas
df = pd.read_excel("Puebla\huauchi ab14.xls")
df.head()

,fecha,DirViento,DirRafaga,RapViento,RapRafaga,TempAire,HumRelativa,PresBarometric,Precipitacion,RadSolar,nombre_estacion
0,2014-04-01 00:00:00,66,312,2.5,5.5,23.2,70,846.0,0.0,140,"HUAUCHINANGO, PUEBLA."
1,2014-04-01 00:10:00,16,37,1.4,3.9,22.7,72,846.0,0.0,67,"HUAUCHINANGO, PUEBLA."
2,2014-04-01 00:20:00,28,50,1.3,2.9,22.3,73,846.1,0.0,26,"HUAUCHINANGO, PUEBLA."
3,2014-04-01 00:30:00,17,354,1.6,2.9,21.8,74,846.2,0.0,15,"HUAUCHINANGO, PUEBLA."
4,2014-04-01 00:40:00,290,346,2.0,3.8,21.3,75,846.2,0.0,5,"HUAUCHINANGO, PUEBLA."

In [4]:
#Se crea una lista de palabras a buscar
lista = ['HumRelativa', 'TempAire', 'Precipitacion']
#Se obtine el nombre de las columnas en donde se quiere buscar
listaColumnas = df.columns.values
#variable en donde se guardara la palabra con mas parecido
masParecido = []
for i in lista:
    masAlto, porcentaje = process.extractOne(i,listaColumnas)
    masParecido.append(masAlto)
#Se crea un dataFrame en donde solo seleccionamos las columnas cuyo nombre es mas parecido a la lista dada
final = pd.DataFrame()
final[lista] = df[masParecido]
#Mostramos el resultado
final.head()

   HumRelativa  TempAire  Precipitacion
0           70      23.2            0.0
1           72      22.7            0.0
2           73      22.3            0.0
3           74      21.8            0.0
4           75      21.3            0.0